### ISSUE TITLE
Kibana Comments app for 7.4

### ISSUE THREAD

**Issue by ajitrepal** [gwintzer/kibana-comments-app-plugin#27]
Hi,
Is it possible to make use of kibana-comments-app-plugin for newer kibana version of 7.4 by making any changes/updates in existing plugin?
Currently I am using it for Kibana 6.5.

**Comment by gwintzer** [comment]
Hi, 
v7.4.0 release is available here :
https://github.com/gwintzer/kibana-comments-app-plugin/releases/tag/7.4.0
