### ISSUE TITLE
forward some headers

### ISSUE THREAD

**Issue by jpparis-orange** [gwintzer/kibana-comments-app-plugin#9]
Would it be possible to forward the following headers 
- cookie,
- authorization,
- x-proxy-user,
- x-proxy-roles

At the moment, app commits can not list the indices when I secure my elasticsearch with searchguard

**Comment by gwintzer** [comment]
client elasticsearch : 

host or hosts | String, String[], Object[] — Specify the hosts that this client will connect to.  ... 
Host objects can help enforce path-prefixes, **default headers** and query strings, ...

see https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/host-reference.html
